### ISSUE TITLE
Error in per slice reference region quantification

### ISSUE THREAD

**Issue by briannnagurdon** [Neural-Systems-at-UIO/nutil#221] opened 2021-08-18 13:02 UTC
The load quantification for the slice reference regions is an incorrect calculation of the output object pixel/region pixel values. The listed load per region in each output slice file does not match this calculation. This error was seen across output from multiple versions of Nutil including the most recent v6.

**Comment by sharoncy** [comment] 2021-08-18 15:55
Brianna has sent me files so I will investigate.

**Comment by sharoncy** [comment] 2021-08-20 08:13
We found the source of the load error. In the RefAtlasReg slice reports the load was calculated by object pixels /region area - it should have been object pixels/ region pixels. So the load error appears on application of a pixel scale other than 1 (with a pixel scale of 1 the region area = region pixels). I didn't include a pixel scale in the ground truth dataset used for testing, which is why it wasn't picked up earlier. Sorry about that!

I noticed another discrepancy in your reports relative to the ones I produced here with your segmentations, atlas maps and NUT file. It looks like the areas in your reports have been calculated based on a pixel scale of 4. The areas in my reports were calculated based on a pixel scale of 1.3061, which is what was entered in the NUT file. Any idea what's going on here? Did you use a pixel scale of 4 to generate your reports and copied over the wrong NUT file? Or is this a potential bug? We can communicate on slack about this, just adding it here for our record. We should get to the bottom of this before we publish a new version.

**Comment by sharoncy** [comment] 2021-08-23 12:41
The pixel scale issue is not a bug, as suspected a pixel scale of 4 was used to generate the reports.

**Comment by Majpuc** [comment] 2021-09-03 09:17
@sharoncy can we proceed with v6.6 release?

**Comment by Majpuc** [comment] 2021-10-01 09:56
Error resolved. Closing 01.oct.2021

**Closed by Majpuc** 2021-10-01 09:56 UTC
Labels: bug
